version: "3.9"

services:
  front:
    # образ
    # проброс портов
    # зависимость от api
  api:
    # секция билд
    # зависимость от контейнера pg и migrations
    # волюм с конфигурацией
  migrations:
    # секция билд
    # зависимость от контейнера pg
    # волюм с конфигурацией
    # команда для применения миграций
  postgres:
    # образ
    # переменные окружения для автоматического создания БД, пользователя и пароля
    # healthcheck для БД
    # волюм для данных БД